# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=120, verbose_name='Başlık')),
                ('metin', models.TextField(verbose_name='Yazı')),
                ('yayim_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf Ekle')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-yayim_tarihi', 'id'],
            },
        ),
    ]
