# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 19:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170410_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-yayim_tarihi', 'slug']},
        ),
        migrations.AlterField(
            model_name='post',
            name='metin',
            field=ckeditor.fields.RichTextField(verbose_name='Yazı'),
        ),
    ]
